# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Model2SAS_UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(986, 717)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_2)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_control = QtWidgets.QGroupBox(self.tab)
        self.groupBox_control.setObjectName("groupBox_control")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_control)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_browseStlFile = QtWidgets.QPushButton(self.groupBox_control)
        self.pushButton_browseStlFile.setObjectName("pushButton_browseStlFile")
        self.gridLayout_2.addWidget(self.pushButton_browseStlFile, 0, 1, 1, 1)
        self.lineEdit_stlFile = QtWidgets.QLineEdit(self.groupBox_control)
        self.lineEdit_stlFile.setObjectName("lineEdit_stlFile")
        self.gridLayout_2.addWidget(self.lineEdit_stlFile, 0, 0, 1, 1)
        self.graphicsView_stlModel = QtWidgets.QGraphicsView(self.groupBox_control)
        self.graphicsView_stlModel.setObjectName("graphicsView_stlModel")
        self.gridLayout_2.addWidget(self.graphicsView_stlModel, 2, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.groupBox_control)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_control, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_mathControl = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_mathControl.setObjectName("groupBox_mathControl")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_mathControl)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lineEdit_pyFile_math = QtWidgets.QLineEdit(self.groupBox_mathControl)
        self.lineEdit_pyFile_math.setObjectName("lineEdit_pyFile_math")
        self.gridLayout_8.addWidget(self.lineEdit_pyFile_math, 0, 1, 1, 1)
        self.pushButton_browsePyFile_math = QtWidgets.QPushButton(self.groupBox_mathControl)
        self.pushButton_browsePyFile_math.setObjectName("pushButton_browsePyFile_math")
        self.gridLayout_8.addWidget(self.pushButton_browsePyFile_math, 0, 2, 1, 1)
        self.tableView_params_math = QtWidgets.QTableView(self.groupBox_mathControl)
        self.tableView_params_math.setObjectName("tableView_params_math")
        self.gridLayout_8.addWidget(self.tableView_params_math, 1, 0, 1, 3)
        self.gridLayout_4.addWidget(self.groupBox_mathControl, 0, 0, 1, 1)
        self.groupBox_pyFileContent = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_pyFileContent.setObjectName("groupBox_pyFileContent")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_pyFileContent)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.textBrowser_pyFileContent = QtWidgets.QTextBrowser(self.groupBox_pyFileContent)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(11)
        self.textBrowser_pyFileContent.setFont(font)
        self.textBrowser_pyFileContent.setObjectName("textBrowser_pyFileContent")
        self.gridLayout_5.addWidget(self.textBrowser_pyFileContent, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_pyFileContent, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton_chooseCrysolPath = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_chooseCrysolPath.setObjectName("pushButton_chooseCrysolPath")
        self.gridLayout_7.addWidget(self.pushButton_chooseCrysolPath, 1, 3, 1, 1)
        self.lineEdit_interval = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_interval.setObjectName("lineEdit_interval")
        self.gridLayout_7.addWidget(self.lineEdit_interval, 0, 1, 1, 2)
        self.pushButton_genPointsInModel = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_genPointsInModel.setObjectName("pushButton_genPointsInModel")
        self.gridLayout_7.addWidget(self.pushButton_genPointsInModel, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 0, 0, 1, 1)
        self.checkBox_useCrysol = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_useCrysol.setChecked(False)
        self.checkBox_useCrysol.setObjectName("checkBox_useCrysol")
        self.gridLayout_7.addWidget(self.checkBox_useCrysol, 1, 0, 1, 1)
        self.label_crysolPath = QtWidgets.QLabel(self.groupBox)
        self.label_crysolPath.setObjectName("label_crysolPath")
        self.gridLayout_7.addWidget(self.label_crysolPath, 1, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEdit_Qmax = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Qmax.setObjectName("lineEdit_Qmax")
        self.gridLayout_7.addWidget(self.lineEdit_Qmax, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 4, 0, 1, 1)
        self.lineEdit_lmax = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_lmax.setObjectName("lineEdit_lmax")
        self.gridLayout_7.addWidget(self.lineEdit_lmax, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 4, 2, 1, 1)
        self.pushButton_calcSaxs = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_calcSaxs.setObjectName("pushButton_calcSaxs")
        self.gridLayout_7.addWidget(self.pushButton_calcSaxs, 4, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_pointsView = QtWidgets.QGroupBox(self.frame)
        self.groupBox_pointsView.setObjectName("groupBox_pointsView")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_pointsView)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.graphicsView_pointsModel = QtWidgets.QGraphicsView(self.groupBox_pointsView)
        self.graphicsView_pointsModel.setObjectName("graphicsView_pointsModel")
        self.gridLayout_6.addWidget(self.graphicsView_pointsModel, 0, 0, 1, 2)
        self.pushButton_savePointsFile = QtWidgets.QPushButton(self.groupBox_pointsView)
        self.pushButton_savePointsFile.setObjectName("pushButton_savePointsFile")
        self.gridLayout_6.addWidget(self.pushButton_savePointsFile, 1, 1, 1, 1)
        self.label_pointsNum = QtWidgets.QLabel(self.groupBox_pointsView)
        self.label_pointsNum.setObjectName("label_pointsNum")
        self.gridLayout_6.addWidget(self.label_pointsNum, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_pointsView)
        self.groupBox_saxsPlot = QtWidgets.QGroupBox(self.frame)
        self.groupBox_saxsPlot.setObjectName("groupBox_saxsPlot")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_saxsPlot)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_saveSaxsPlot = QtWidgets.QPushButton(self.groupBox_saxsPlot)
        self.pushButton_saveSaxsPlot.setObjectName("pushButton_saveSaxsPlot")
        self.gridLayout_3.addWidget(self.pushButton_saveSaxsPlot, 1, 0, 1, 1)
        self.graphicsView_saxsPlot = QtWidgets.QGraphicsView(self.groupBox_saxsPlot)
        self.graphicsView_saxsPlot.setObjectName("graphicsView_saxsPlot")
        self.gridLayout_3.addWidget(self.graphicsView_saxsPlot, 0, 0, 1, 2)
        self.pushButton_saveSaxsData = QtWidgets.QPushButton(self.groupBox_saxsPlot)
        self.pushButton_saveSaxsData.setObjectName("pushButton_saveSaxsData")
        self.gridLayout_3.addWidget(self.pushButton_saveSaxsData, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_saxsPlot)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.frame)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_control.setTitle(_translate("MainWindow", "Choose .stl File"))
        self.pushButton_browseStlFile.setText(_translate("MainWindow", "Browse"))
        self.label.setText(_translate("MainWindow", "stl Model View"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "From STL File"))
        self.groupBox_mathControl.setTitle(_translate("MainWindow", "Choose .py file"))
        self.pushButton_browsePyFile_math.setText(_translate("MainWindow", "Browse"))
        self.groupBox_pyFileContent.setTitle(_translate("MainWindow", ".py file content"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "From Math Description"))
        self.groupBox.setTitle(_translate("MainWindow", "Control"))
        self.pushButton_chooseCrysolPath.setText(_translate("MainWindow", "Choose crysol.exe"))
        self.pushButton_genPointsInModel.setText(_translate("MainWindow", "Generate points model"))
        self.label_3.setText(_translate("MainWindow", "points interval = "))
        self.checkBox_useCrysol.setText(_translate("MainWindow", "use crysol"))
        self.label_crysolPath.setText(_translate("MainWindow", "choose Crysol path"))
        self.label_2.setText(_translate("MainWindow", "Q_max = "))
        self.label_4.setText(_translate("MainWindow", "l_max = "))
        self.label_5.setText(_translate("MainWindow", "in reverse Angstrom"))
        self.label_6.setText(_translate("MainWindow", "max 50"))
        self.pushButton_calcSaxs.setText(_translate("MainWindow", "Calculate SAXS curve"))
        self.groupBox_pointsView.setTitle(_translate("MainWindow", "Points Model View"))
        self.pushButton_savePointsFile.setText(_translate("MainWindow", "Save PDB File"))
        self.label_pointsNum.setText(_translate("MainWindow", "*** points"))
        self.groupBox_saxsPlot.setTitle(_translate("MainWindow", "SAXS Plot"))
        self.pushButton_saveSaxsPlot.setText(_translate("MainWindow", "Save SAXS Plot"))
        self.pushButton_saveSaxsData.setText(_translate("MainWindow", "Save SAXS Data File"))
