# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Model2SAS_UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget


class Ui_mainWindow(QWidget):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_pointsView = QtWidgets.QGroupBox(self.tab)
        self.groupBox_pointsView.setObjectName("groupBox_pointsView")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_pointsView)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.graphicsView_pointsModel = QtWidgets.QGraphicsView(self.groupBox_pointsView)
        self.graphicsView_pointsModel.setObjectName("graphicsView_pointsModel")
        self.verticalLayout_3.addWidget(self.graphicsView_pointsModel)
        self.gridLayout.addWidget(self.groupBox_pointsView, 0, 1, 1, 1)
        self.groupBox_stlView = QtWidgets.QGroupBox(self.tab)
        self.groupBox_stlView.setObjectName("groupBox_stlView")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_stlView)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphicsView_stlModel = QtWidgets.QGraphicsView(self.groupBox_stlView)
        self.graphicsView_stlModel.setObjectName("graphicsView_stlModel")
        self.verticalLayout_2.addWidget(self.graphicsView_stlModel)
        self.gridLayout.addWidget(self.groupBox_stlView, 2, 0, 1, 1)
        self.groupBox_saxsPlot = QtWidgets.QGroupBox(self.tab)
        self.groupBox_saxsPlot.setObjectName("groupBox_saxsPlot")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_saxsPlot)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_saveSaxsPlot = QtWidgets.QPushButton(self.groupBox_saxsPlot)
        self.pushButton_saveSaxsPlot.setObjectName("pushButton_saveSaxsPlot")
        self.gridLayout_3.addWidget(self.pushButton_saveSaxsPlot, 1, 0, 1, 1)
        self.pushButton_saveSaxsData = QtWidgets.QPushButton(self.groupBox_saxsPlot)
        self.pushButton_saveSaxsData.setObjectName("pushButton_saveSaxsData")
        self.gridLayout_3.addWidget(self.pushButton_saveSaxsData, 1, 1, 1, 1)
        self.graphicsView_saxsPlot = QtWidgets.QGraphicsView(self.groupBox_saxsPlot)
        self.graphicsView_saxsPlot.setObjectName("graphicsView_saxsPlot")
        self.gridLayout_3.addWidget(self.graphicsView_saxsPlot, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox_saxsPlot, 2, 1, 1, 1)
        self.groupBox_control = QtWidgets.QGroupBox(self.tab)
        self.groupBox_control.setObjectName("groupBox_control")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_control)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_genPointsInModel = QtWidgets.QPushButton(self.groupBox_control)
        self.pushButton_genPointsInModel.setObjectName("pushButton_genPointsInModel")
        self.gridLayout_2.addWidget(self.pushButton_genPointsInModel, 1, 2, 1, 1)
        self.pushButton_calcSaxs = QtWidgets.QPushButton(self.groupBox_control)
        self.pushButton_calcSaxs.setObjectName("pushButton_calcSaxs")
        self.gridLayout_2.addWidget(self.pushButton_calcSaxs, 4, 0, 1, 1)
        self.checkBox_useCrysol = QtWidgets.QCheckBox(self.groupBox_control)
        self.checkBox_useCrysol.setChecked(False)
        self.checkBox_useCrysol.setObjectName("checkBox_useCrysol")
        self.gridLayout_2.addWidget(self.checkBox_useCrysol, 3, 0, 1, 1)
        self.pushButton_chooseCrysolPath = QtWidgets.QPushButton(self.groupBox_control)
        self.pushButton_chooseCrysolPath.setObjectName("pushButton_chooseCrysolPath")
        self.gridLayout_2.addWidget(self.pushButton_chooseCrysolPath, 3, 2, 1, 1)
        self.pushButton_browseStlFile = QtWidgets.QPushButton(self.groupBox_control)
        self.pushButton_browseStlFile.setObjectName("pushButton_browseStlFile")
        self.gridLayout_2.addWidget(self.pushButton_browseStlFile, 0, 2, 1, 1)
        self.lineEdit_interval = QtWidgets.QLineEdit(self.groupBox_control)
        self.lineEdit_interval.setObjectName("lineEdit_interval")
        self.gridLayout_2.addWidget(self.lineEdit_interval, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_control)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_stlFile = QtWidgets.QLineEdit(self.groupBox_control)
        self.lineEdit_stlFile.setObjectName("lineEdit_stlFile")
        self.gridLayout_2.addWidget(self.lineEdit_stlFile, 0, 1, 1, 1)
        self.label_crysolPath = QtWidgets.QLabel(self.groupBox_control)
        self.label_crysolPath.setObjectName("label_crysolPath")
        self.gridLayout_2.addWidget(self.label_crysolPath, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_control)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_control)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.pushButton_savePointsFile = QtWidgets.QPushButton(self.groupBox_control)
        self.pushButton_savePointsFile.setObjectName("pushButton_savePointsFile")
        self.gridLayout_2.addWidget(self.pushButton_savePointsFile, 2, 2, 1, 1)
        self.comboBox_choosePointsFileType = QtWidgets.QComboBox(self.groupBox_control)
        self.comboBox_choosePointsFileType.setObjectName("comboBox_choosePointsFileType")
        self.comboBox_choosePointsFileType.addItem("")
        self.comboBox_choosePointsFileType.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_choosePointsFileType, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_control, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Model2SAS"))
        self.groupBox_pointsView.setTitle(_translate("mainWindow", "points model view"))
        self.groupBox_stlView.setTitle(_translate("mainWindow", "stl model view"))
        self.groupBox_saxsPlot.setTitle(_translate("mainWindow", "SAXS plot"))
        self.pushButton_saveSaxsPlot.setText(_translate("mainWindow", "Save SAXS plot"))
        self.pushButton_saveSaxsData.setText(_translate("mainWindow", "Save SAXS data file"))
        self.groupBox_control.setTitle(_translate("mainWindow", "Control"))
        self.pushButton_genPointsInModel.setText(_translate("mainWindow", "Generate points model"))
        self.pushButton_calcSaxs.setText(_translate("mainWindow", "Calculate SAXS curve"))
        self.checkBox_useCrysol.setText(_translate("mainWindow", "use crysol"))
        self.pushButton_chooseCrysolPath.setText(_translate("mainWindow", "Choose crysol.exe"))
        self.pushButton_browseStlFile.setText(_translate("mainWindow", "Browse"))
        self.label_2.setText(_translate("mainWindow", "Choose .stl file"))
        self.label_crysolPath.setText(_translate("mainWindow", "choose Crysol path"))
        self.label_3.setText(_translate("mainWindow", "points interval = "))
        self.label_4.setText(_translate("mainWindow", "save points model"))
        self.pushButton_savePointsFile.setText(_translate("mainWindow", "Ssave"))
        self.comboBox_choosePointsFileType.setItemText(0, _translate("mainWindow", "PDB file"))
        self.comboBox_choosePointsFileType.setItemText(1, _translate("mainWindow", "xyz file"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "from stl file"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainWindow", "from math description"))
