# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mathmodelView.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mathmodelView(object):
    def setupUi(self, mathmodelView):
        mathmodelView.setObjectName("mathmodelView")
        mathmodelView.resize(614, 470)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        mathmodelView.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(mathmodelView)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(mathmodelView)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.pushButton_saveFigure = QtWidgets.QPushButton(mathmodelView)
        self.pushButton_saveFigure.setObjectName("pushButton_saveFigure")
        self.gridLayout.addWidget(self.pushButton_saveFigure, 1, 1, 1, 1)

        self.retranslateUi(mathmodelView)
        QtCore.QMetaObject.connectSlotsByName(mathmodelView)

    def retranslateUi(self, mathmodelView):
        _translate = QtCore.QCoreApplication.translate
        mathmodelView.setWindowTitle(_translate("mathmodelView", "math model view"))
        self.pushButton_saveFigure.setText(_translate("mathmodelView", "Save figure"))
