# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newProject.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newProject(object):
    def setupUi(self, newProject):
        newProject.setObjectName("newProject")
        newProject.setWindowModality(QtCore.Qt.ApplicationModal)
        newProject.resize(400, 105)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        newProject.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(newProject)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(newProject)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_newProject = QtWidgets.QPushButton(newProject)
        self.pushButton_newProject.setObjectName("pushButton_newProject")
        self.gridLayout.addWidget(self.pushButton_newProject, 2, 3, 1, 1)
        self.pushButton_browse = QtWidgets.QPushButton(newProject)
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.gridLayout.addWidget(self.pushButton_browse, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(newProject)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_path = QtWidgets.QLineEdit(newProject)
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.gridLayout.addWidget(self.lineEdit_path, 1, 1, 1, 1)
        self.lineEdit_name = QtWidgets.QLineEdit(newProject)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.gridLayout.addWidget(self.lineEdit_name, 0, 1, 1, 3)

        self.retranslateUi(newProject)
        QtCore.QMetaObject.connectSlotsByName(newProject)

    def retranslateUi(self, newProject):
        _translate = QtCore.QCoreApplication.translate
        newProject.setWindowTitle(_translate("newProject", "New Project"))
        self.label.setText(_translate("newProject", "New Project Name"))
        self.pushButton_newProject.setText(_translate("newProject", "New Project"))
        self.pushButton_browse.setText(_translate("newProject", "Browse"))
        self.label_2.setText(_translate("newProject", "New Project Path"))
