# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\plotView.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_plotView(object):
    def setupUi(self, plotView):
        plotView.setObjectName("plotView")
        plotView.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(plotView)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(plotView)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 3)
        self.pushButton_saveFigure = QtWidgets.QPushButton(plotView)
        self.pushButton_saveFigure.setObjectName("pushButton_saveFigure")
        self.gridLayout.addWidget(self.pushButton_saveFigure, 1, 2, 1, 1)
        self.label_text = QtWidgets.QLabel(plotView)
        self.label_text.setObjectName("label_text")
        self.gridLayout.addWidget(self.label_text, 1, 0, 1, 2)

        self.retranslateUi(plotView)
        QtCore.QMetaObject.connectSlotsByName(plotView)

    def retranslateUi(self, plotView):
        _translate = QtCore.QCoreApplication.translate
        plotView.setWindowTitle(_translate("plotView", "Plot View"))
        self.pushButton_saveFigure.setText(_translate("plotView", "Save figure"))
        self.label_text.setText(_translate("plotView", "interval = "))
