# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pointsWithSldView.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pointsWithSldView(object):
    def setupUi(self, pointsWithSldView):
        pointsWithSldView.setObjectName("pointsWithSldView")
        pointsWithSldView.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(pointsWithSldView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(pointsWithSldView)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.label_interval = QtWidgets.QLabel(pointsWithSldView)
        self.label_interval.setObjectName("label_interval")
        self.verticalLayout.addWidget(self.label_interval)

        self.retranslateUi(pointsWithSldView)
        QtCore.QMetaObject.connectSlotsByName(pointsWithSldView)

    def retranslateUi(self, pointsWithSldView):
        _translate = QtCore.QCoreApplication.translate
        pointsWithSldView.setWindowTitle(_translate("pointsWithSldView", "All Points with SLD"))
        self.label_interval.setText(_translate("pointsWithSldView", "interval = "))
