# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sasdataView.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sasdataView(object):
    def setupUi(self, sasdataView):
        sasdataView.setObjectName("sasdataView")
        sasdataView.resize(400, 300)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        sasdataView.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(sasdataView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(sasdataView)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)

        self.retranslateUi(sasdataView)
        QtCore.QMetaObject.connectSlotsByName(sasdataView)

    def retranslateUi(self, sasdataView):
        _translate = QtCore.QCoreApplication.translate
        sasdataView.setWindowTitle(_translate("sasdataView", "SAS data view"))
