# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\sasdataView.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sasdataView(object):
    def setupUi(self, sasdataView):
        sasdataView.setObjectName("sasdataView")
        sasdataView.resize(400, 300)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        sasdataView.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(sasdataView)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(sasdataView)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(298, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.pushButton_saveFigure = QtWidgets.QPushButton(sasdataView)
        self.pushButton_saveFigure.setObjectName("pushButton_saveFigure")
        self.gridLayout.addWidget(self.pushButton_saveFigure, 1, 1, 1, 1)

        self.retranslateUi(sasdataView)
        QtCore.QMetaObject.connectSlotsByName(sasdataView)

    def retranslateUi(self, sasdataView):
        _translate = QtCore.QCoreApplication.translate
        sasdataView.setWindowTitle(_translate("sasdataView", "SAS data view"))
        self.pushButton_saveFigure.setText(_translate("sasdataView", "Save figure"))
