# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\stlmodelView.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_stlmodelView(object):
    def setupUi(self, stlmodelView):
        stlmodelView.setObjectName("stlmodelView")
        stlmodelView.resize(457, 416)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        stlmodelView.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(stlmodelView)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(stlmodelView)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(355, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.pushButton_saveFigure = QtWidgets.QPushButton(stlmodelView)
        self.pushButton_saveFigure.setObjectName("pushButton_saveFigure")
        self.gridLayout.addWidget(self.pushButton_saveFigure, 1, 1, 1, 1)

        self.retranslateUi(stlmodelView)
        QtCore.QMetaObject.connectSlotsByName(stlmodelView)

    def retranslateUi(self, stlmodelView):
        _translate = QtCore.QCoreApplication.translate
        stlmodelView.setWindowTitle(_translate("stlmodelView", "stl model view"))
        self.pushButton_saveFigure.setText(_translate("stlmodelView", "Save figure"))
