# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stlmodelView.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_stlmodelView(object):
    def setupUi(self, stlmodelView):
        stlmodelView.setObjectName("stlmodelView")
        stlmodelView.resize(457, 416)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        stlmodelView.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(stlmodelView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(stlmodelView)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)

        self.retranslateUi(stlmodelView)
        QtCore.QMetaObject.connectSlotsByName(stlmodelView)

    def retranslateUi(self, stlmodelView):
        _translate = QtCore.QCoreApplication.translate
        stlmodelView.setWindowTitle(_translate("stlmodelView", "stl model view"))
