# -*- coding: utf-8 -*-

# Not generated by pyuic5


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

import matplotlib
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT
from matplotlib.figure import Figure


matplotlib.use("Qt5Agg")


class MplCanvas(FigureCanvasQTAgg):
    def __init__(self, width=5, height=4, dpi=100):
        self.fig = Figure(figsize=(width, height), dpi=dpi)
        super().__init__(self.fig)


class Ui_plotView(QMainWindow):

    def __init__(self):

        super(Ui_plotView, self).__init__()

        self.resize(600, 450)

        self.canvas = MplCanvas()
        self.toolbar = NavigationToolbar2QT(self.canvas, self)
        self.label_text = QtWidgets.QLabel()
        self.label_text.setFixedHeight(20)

        self.vBoxLayout = QtWidgets.QVBoxLayout()
        self.vBoxLayout.addWidget(self.toolbar)
        self.vBoxLayout.addWidget(self.canvas)
        self.vBoxLayout.addWidget(self.label_text)

        # Create a placeholder widget to hold our toolbar and canvas.
        widget = QtWidgets.QWidget()
        widget.setLayout(self.vBoxLayout)
        self.setCentralWidget(widget)
        
        self.retranslateUi()


    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("plotView", "Plot View"))
        self.label_text.setText(_translate("plotView", "interval = "))


if __name__ == '__main__':
    def plot(fig):
        ax = fig.add_subplot(111)
        ax.plot([0, 1, 2, 3, 4], [10, 1, 20, 3, 40])

    from PyQt5.QtWidgets import QApplication
    import sys

    app = QApplication(sys.argv)
    w = Ui_plotView()
    #ax = w.canvas.fig.add_subplot(111)
    #ax.plot([0, 1, 2, 3, 4], [10, 1, 20, 3, 40])
    plot(w.canvas.fig)
    w.show()
    app.exec_()
